# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TrailLengthCalc
                                 A QGIS plugin
 Calculate the length of line feautures in a layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-05-29
        copyright            : (C) 2022 by Luis Monteiro
        email                : g20210017@novaims.unl.pt
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TrailLengthCalc class from file TrailLengthCalc.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .trail_length_calc import TrailLengthCalc
    return TrailLengthCalc(iface)
